### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by smb20200615** [gtonkinhill/panaroo#111]
Hello,

Thank you for your wonderful tool. I have three questions. 1) I often get output such as group_2686 in the gene_presence matrix. Where can I find the genomes that contributed to this gene cluster? 2) Also, I am interested in annotating the genes reported in the gene-presence absence matrix. Where can I get the associated gene sequence for example for group_2686 to be used annotation via eggnog? 3) Finally, I was wondering if there is a way to make a manhattan plot from the output from panaroo + pyseer. I can't find the location of such genes in the genome (GFF file?). Is that reported somewhere in panaroo?

Many thanks!

**Comment by gtonkinhill** [comment]
Hi,

1. The genes for each cluster are given in the `gene_presence_absence.csv` file.
2. The gene names given in this file can be associated with the sequence and annotations by looking for their entry in the `gene_data.csv` file.
3. I'm afraid not. This is a pretty tricky problem we are currently working on. As the genes are located in a graph rather than a single reference, it is not straightforward to work out what a sensible distance is between two genes. Taking the shortest path in the graph tends to give pretty poor results as mobile genetic elements can cause issues leading to very short distance estimates.

Hopefully this helps!

**Comment by cizydorczyk** [comment]
Hi,

Is there an output file that contains representative genes for each group found in the gene_presence_absence.csv file?

I understand I can find an individual sample's gene sequence in the gene_data.csv file (or in conjunction with the combined_DNA_CDS.fasta file), but are representative genes for each cluster stored somewhere accessible?

I ask as I am interested in performing an enrichment analysis and was thinking I could use the representative sequence for each cluster as input to the analysis, if such a sequence is available.

Thanks,
Conrad

**Comment by gtonkinhill** [comment]
Hi Conrad,

We include a concatenated set of representative genes in the `pan_genome_reference.fa` file. 

However, we don't currently provide these as seperate gene sequences. The `final_graph.gml` file includes a `centroid` attribute which could be used to decide which genes from the `gene_data.csv` to use as representatives. 

Depending on exactly how you are using them it might be simpler to take the longest sequence in a cluster as the representative.

**Comment by cizydorczyk** [comment]
Thanks for the update. I deleted my post as I figured it out after
re-reading the documentation carefully. The pan_genome_reference.fa file is
exactly what I needed.

Thanks!
