### ISSUE TITLE
Inconsistencies between graph and gene_data with panaroo-merge

### ISSUE THREAD

**Issue by Danderson123** [gtonkinhill/panaroo#112]
Hey Gerry, 

I hope you're doing well! I'm currently using panaroo v.1.27 as part of a larger pipeline and have noticed some of the "geneIDs" associated with each node in the graph are not present in the "clustering_ID" column of gene_data.csv after merging two outputs. Any idea why this may be the case? I did not notice this when running panaroo on each dataset individually or when using the same data in a single panaroo run. I have attached an example output where "5_0_30" is present in "geneIDs" but not in "clustering_ID" for node "group_300". Looking at gene_presence_absence.csv, the annotation ID of this is "cds-WP_024271669.1" which does not seem to be present in gene_data.csv at all.

thanks, 
Daniel
[gene_data.zip](https://github.com/gtonkinhill/panaroo/files/6398716/gene_data.zip)

**Comment by gtonkinhill** [comment]
Hi Daniel,

Thank's for pointing this out. It should be present so I'm not sure exactly what is going on. 
Is it possible for you to send me the input data so that I can have a go at reproducing the issue? If you already have the seperate directories that you ran `panaroo-merge` on that would be great.

Cheers,
Gerry

**Comment by Danderson123** [comment]
Hi Gerry,

I don't have the exact inputs for the example above but here is another example and a list of geneIDs that seem to be missing from the merged gene_data.csv. 

The command I used to generate the initial outputs was:
`panaroo -i sample_gffs/*.gff -o panaroo_run_2 --clean-mode sensitive -t 4`

And the command to merge the outputs:
`panaroo-merge -d panaroo_run_1 panaroo_run_2  -o panaroo_merged_output -t 4`

Thanks,
Daniel

[panaroo_run_1.zip](https://github.com/gtonkinhill/panaroo/files/6403464/panaroo_run_1.zip)
[missing_geneIDs.txt](https://github.com/gtonkinhill/panaroo/files/6403462/missing_geneIDs.txt)
[panaroo_merged_output.zip](https://github.com/gtonkinhill/panaroo/files/6403463/panaroo_merged_output.zip)
[panaroo_run_2.zip](https://github.com/gtonkinhill/panaroo/files/6403465/panaroo_run_2.zip)

**Comment by gtonkinhill** [comment]
Hi Daniel,

Sorry it's taken me a while to get to this. I'm having trouble reproducing the issue but think it might have something to do with the version of networkx that panaroo is using. Are you able to check which version you have installed using `pip freeze`?

I'm currently testing using version 2.5.1

**Comment by Danderson123** [comment]
Hi Gerry, 

I'm glad this does not seem to be the result of a larger problem. Apparently I am also using networkx v2.5.1. Could I possibly see the output of your pip freeze to see what combination of package versions avoids this issue?

Thanks,
Daniel

**Comment by gtonkinhill** [comment]
Hi Daniel,

I've copied the output of `pip freeze` below. 

In debugging I'm focusing on the endonuclease gene labeled as `group_2160` in your merged graph file. This includes the genes `0_7_49` and `3_5_40` (cds-WP_000185526.1) from run 1.  When I run the merge command as `panaroo-merge -d panaroo_run_1 panaroo_run_2 -o panaroo_merged_output -t 4` these gene labels remain  the same in the merged graph. 

However, if I swap the order of the input files they are labelled as `5_7_49` and `8_5_40` which matches your merged graph. In both instances they appear in the merged `gene_data.csv` file but are missing in your version of the merge. I'm wondering whether this might be due to an issue with the program crashing and perhaps restarting? I was also thinking it might have something to do with the multithreaded option so was wondering if you could try running the merge operation again with `-t 1`

```
argcomplete==1.11.1
argh==0.26.2
ariba==2.14.5
attrs==20.3.0
beautifulsoup4==4.9.1
biopython==1.76
certifi==2020.12.5
cycler==0.10.0
decorator==4.4.2
DendroPy==4.4.0
edlib==1.2.3.post1
gffutils==0.9
gubbins==1.4.9
importlib-metadata==1.5.0
iniconfig==1.1.1
intbitset==2.4.0
joblib==0.14.1
kiwisolver==1.1.0
llvmlite==0.31.0
matplotlib==3.2.0
mungo==0.1a1
networkx==2.5.1
numba==0.48.0
numpy==1.18.1
packaging==20.9
pairsnp==0.0.5
panaroo==1.2.7
pandas==1.1.5
plotly==4.5.4
pluggy==0.13.1
py==1.10.0
pyfaidx==0.5.5.2
pyfastaq==3.17.0
pyfastx==0.6.12
pymummer==0.10.3
pyparsing==2.4.6
PyQt5==5.12.3
PyQt5-sip==4.19.18
PyQtWebEngine==5.12.1
pysam==0.15.3
pytest==6.2.2
python-dateutil==2.8.1
pytz==2020.5
retrying==1.3.3
scikit-learn==0.22.2.post1
scipy==1.1.0
simplejson==3.8.1
six==1.14.0
sklearn==0.0
soupsieve==2.0.1
toml==0.10.2
tornado==6.0.4
tqdm==4.7.2
yapf==0.30.0
zipp==3.1.0
```

**Comment by Danderson123** [comment]
Hey Gerry,

Changing my package versions sorted out the issue. I tried re-running the command on 1 thread and experienced the same problem so cut my losses and set up a fresh virtual env using the versions you shared. Thanks for your help!

**Comment by gtonkinhill** [comment]
Hey Daniel,

Glad it's sorted out! If you've still got it on hand would you mind sharing the package versions you used originally? It might be useful later on to know if a certain version causes issues.

**Comment by Danderson123** [comment]
Apologies but I don't have these anymore! Although I did test different combinations of package versions installed in my base conda env (networkx 2.5, matplotlib 3.3.4, numpy 1.2.0, scipy 1.6.0 & pandas 1.2.1) in case these were the source but have not been able to recreate the bug. I'll go ahead and close the issue, thanks for your help!
