### ISSUE TITLE
Difficulty reproducing results

### ISSUE THREAD

**Issue by cthrnshn** [gtonkinhill/panaroo#134]
I ran panaroo (v1.2.8) multiple times on the same computer using the same parameters and input files but have gotten different results (i.e. different number of core, soft core, shell, cloud, and total genes). I have tried to reproduce my results several times over a period of weeks. Is there a randomized component of the algorithm? I did not see such a description in the paper.

**Comment by gtonkinhill** [comment]
Thanks very much for this. An initial test using the same command did not reproduce the problem so it is likely a version issue or something specific to the set of input files.

I will next try using the same package versions you have. If it's possible to send me a small subset of files that reproduce the issue that would help a lot with narrowing things down.

**Comment by nzmacalasdair** [comment]
Hi @cthrnshn! I was just taking a look through some open issues, and I wonder if this might be something to do with the cd-hit version you are using, as a difference in the numbers of genes seems likely to be the result of a small difference in the initial clustering. Is there any chance that the cd-hit versions might be inconsistent between the two runs? Also, could you possibly check the overall version with `cd-hit -h`?

**Comment by cthrnshn** [comment]
Hi @nzmacalasdair,
Thank you for your questions. I do not think that the issue is inconsistent versions of cd-hit. I am using a HPC system and employ the command `module load cd-hit/4.8.1` to load cd-hit v4.8.1. When I ran `cd-hit -h` after loading, it showed that v4.8.1 was in fact loaded.

**Comment by gtonkinhill** [comment]
This is an old issue but I think it may have been due to a quirk/bug of the gffutils python package which was using the system's temp directory rather than the one created by Panaroo. 
This was quite tricky to identify as it only occurred if multiple instances of gffutils were running at the same time. In this case, they could potentially conflict with each other and give strange results.
This has been fixed in Panaroo v1.4+. I'll close this for now and re-open it if a similar issue is reported again.
