### ISSUE TITLE
Why does ~~ mean?

### ISSUE THREAD

**Issue by smb20200615** [gtonkinhill/panaroo#151]
Hi,

I am using panaroo's presence absence matrix for a GWAS. I was wondering how to differentiate ssl5_1~~~ssl5_2~~~ssl5_3~~~ssl5 and ssl5_2~~~ssl5_3~~~ssl5_1. Are they both different variants of the ssl gene? What about psuK~~~psuK_2~~~RBKS_1~~~psuK_1 where it seems like there are multiple genes separated by ~~. 

I would really appreciate your insights.

**Comment by gtonkinhill** [comment]
Hi,

When Panaroo clusters together gene sequences that have been annotated with different names it combines each name in the cluster using the delimiter `~~~`.

In your first example this is often caused by two paralogous clusters or occasionally the same but diverse copy of the gene occurring in a very different region of the genome in a subset of isolates.

The second example is often caused by inconsistencies in the annotation of a gene. Some gene families can also include a number of different names for different versions of the gene.

I hope this helps!

**Comment by ss8222** [comment]
as an extension to the question above, why does location in the genome matter? Is it because panaroo uses graphical methods and so both location in genome and identity between different copies of the gene both will matter? 

also, tools like pyseer can associate the presence/absence of a genes with the phenotype of interest. If pyseer gives a negative effect size for one paralogue and a positive effect size for another, then it is no longer presence of that gene that is related to the phenotype but rather the variation in that gene since each paralogue is a variant? Or am I misinterpreting this

**Comment by gtonkinhill** [comment]
Yes, Panaroo uses both gene synteny and sequence identity to generate clusters. Synteny is used to seperate paralogous clusters, to collapse diverse gene families and to re-find 'missing' genes.

It may not be the variation within the gene necessarily. Another explanation for those effects could be that having multiple copies of the gene results in a different phenotype or has a fitness cost. Sometimes genes that move around can also be in linkage with other genes that may confer a particular phenotype which could lead to differences in the inferred effect of multiple copies of a paralog.

**Comment by smb20200615** [comment]
Hi, thank you for your prompt reply. I was interested in just presence/absence of genes and correlating that with phenotype so I used the option --merge-paralogs but I am still seeing this behavior. Is there another option you would recommend?

**Comment by gtonkinhill** [comment]
If you are still seeing this behaviour with the `--merge_paralogs` flag then it is likely that the two clusters are quite diverse and are separated on the pangenome. In this case it can be hard to justify merging them. One way of investigating would be to load the `final_graph.gml` file into cytoscape and look for these genes.

If you are confident they should be merged you could try changing the initial sequence identity and length cut-offs panaroo uses to identify potential paralogs. These can be controlled with the `--threshold` and `--len_dif_percent` flags.

**Comment by smb20200615** [comment]
Thank you!
