### ISSUE TITLE
missing sequences in the reference pangenome

### ISSUE THREAD

**Issue by Leytoncito** [gtonkinhill/panaroo#197]
Hi, 

I have a little problem, 
I ran panaroo for my genomes and it worked, however when trying to extract sequences from the reference pangenome there are sequences that don't exist. (i) First when I see the summary of the pan-genome, I realize that there are 6716, then I count the genes with grep (">") which gives 6606 genes as a result. (ii) I get the ids from the "gene_presence_absence*" files. (iii) I extracted with samtools, however this is not the problem, since I checked manually for the existence of the target sequences.

**My question is, why is this happening? Could it be that the mode should be "sensitive", or is it a bug?**.

PD: I'm using the panaroo  v1.2.9

Thanls in advance

Leytoncito.

**Comment by gtonkinhill** [comment]
Hi,

This is probably due to paralogs. Panaroo only includes a single example of each paralog in the pangenome reference. This avoids issues with reads aligning to multiple copies of a gene. 
All instances of paralogous clusters will be included in the summary file and the gene_presence_absence* files unless the merge option has been used.
