### ISSUE TITLE
duplicated clusters with same gene annotations

### ISSUE THREAD

**Issue by herber4** [gtonkinhill/panaroo#213]
Hi Panaroo, 

I am receiving clusters in the output that seem like they should be grouped together (see attached table), for instance, copper resistance protein B, or copB. The attached figure should really just be collapsed into 5-6 genes but is many clusters. 

is this because they don't meet the sequence identity threshold and are thus put into two different clusters?, how do I collapse these? if it is bc of sequencing identity thresholds, at what percent do you recommend running at? 

[Untitled.txt](https://gith
[cop_genes_heatmap2.pdf](https://github.com/gtonkinhill/panaroo/files/10002621/cop_genes_heatmap2.pdf)
ub.com/gtonkinhill/panaroo/files/10002603/Untitled.txt)

best,

Austin

**Comment by gtonkinhill** [comment]
Hi Austin,

This could be to do with the identity threshold but might also be driven by paralogs. To see which genes are paralogs you can look at the paralog category in the `final_graph.gml`. This can be loaded in cytoscape.

It could also be due to sequencing identity thresholds. Particularly if your genomes are quite diverse so that there is considerable diversity even in the core. In this case, you could try adjusting the `--threshold` and `--len_dif_percent` parameters.

If the problem is that the gene family itself is very diverse you could try adjusting the `--family_threshold` parameter.

I hope this helps
