### ISSUE TITLE
Unable to produce aln file 

### ISSUE THREAD

**Issue by ruchitab24** [gtonkinhill/panaroo#244]
Hello,

I am trying to use panaroo to produce a core genome alignment and have run the following command: 

panaroo -i *.gff -o panaroo_results --clean-mode strict --alignment core --aligner mafft --core_threshold 0.98

Using gff files produced from prokka as my input. All outputs of panaroo are written correctly with the exception of the core genome alignment file- I assumed these should be written under the aligned_genes folder but that folder remains empty. I have tried submitting this as a batch job with increasing levels of time and memory but the alignment files are still not produced.  For reference, I am using panaroo version 1.3.3, and installed it using bioconda (using python version 3.9)

Thank you in advance for your help!

**Comment by nzmacalasdair** [comment]
Hello! Apologies for the late response here. 

Can I ask if panaroo exits abnormally or produces an error message? Otherwise, from your description of the issue, it sounds like your core threshold may just be too high, and that no genes are meeting the 98% identity threshold. 

A quick way to check this is to align the entire pangenome (-a pan) and seeing if that produces outputs in the aligned_gene_sequences folder as expected.  The core alignment should be present in the main panaroo output folder as core_gene_alignment.aln.

**Comment by dawnmy** [comment]
I had similar issue: no core gene aln file generated but the summary statistics shows there are 12 core genes and 17 soft core genes. I used `--clean-mode strict` the rest parameters are default. Can I at least extract these core genes to generate MSA myself?

**Comment by gtonkinhill** [comment]
Hi,

Can you please add the exact command you ran and any error messages that occurred?

**Comment by dawnmy** [comment]
after set `-a core` the aln can be generated.
