### ISSUE TITLE
UnboundLocalError: local variable 'prot_outname' referenced before assignment

### ISSUE THREAD

**Issue by fengyuchengdu** [gtonkinhill/panaroo#278]
This was raised when I ran 'panaroo -i *.gff -o panaroo_default' followed by 'panaroo-msa -o panaroo_default -a core --codons', whereas it ran smoothly after removing '--codons' flag.

Many thanks

**Comment by nzmacalasdair** [comment]
Hello! 

Thanks for letting us know about this -- could I just check which version of panaroo you are running?

**Comment by fengyuchengdu** [comment]
Hello!
I'm running Panaroo 1.4.2 (conda installed).

**Comment by nzmacalasdair** [comment]
Thanks! I'm almost positive that this is a bug introduced in 1.4.2 by mistake along with a fix for another issue. If you have the original error message saved, the line number should confirm this. 

This bug should therefore be fixed in commit [ace63a5](https://github.com/gtonkinhill/panaroo/commit/ace63a542525a72a92ab54de733d66f8d6b9b309), and will be installable with conda in the next release.

In the meantime, if you would like to generate codon-based multiple sequence alignments from your panaroo output, you can clone this git repo and manually run the code (with the panaroo conda environment active) by running `python panaroo-msa-runner.py`. Let me know if you have any problems with this!

**Comment by fengyuchengdu** [comment]
thanks!

**Comment by gtonkinhill** [comment]
This should hopefully be resolved in v1.5.0
