### ISSUE TITLE
Biopython deprecation error 

### ISSUE THREAD

**Issue by lucyjanekelly** [gtonkinhill/panaroo#301]
I have tried to install panaroo on an HPC cluster using conda as well as manually. I have python 3.9 loaded into my environment. However, no matter how I install it, when I try to use panaroo it gives this error:

"BiopythonDeprecationWarning: The Bio.Application modules and modules relying on it have been deprecated.

Due to the on going maintenance burden of keeping command line application
wrappers up to date, we have decided to deprecate and eventually remove these
modules.

We instead now recommend building your command line and invoking it directly
with the subprocess module."

Biopython's website says it deprecated python 3.9, but it still has the same error when I tried with a newer python version. I also don't know how to build my command line and invoke it directly with the subprocess module.

**Comment by gtonkinhill** [comment]
Hi,

This appears to be just a warning at the moment. We are in the process of removing the `Bio.Application` module as it has been deprecated.

However, it should still be present within `BioPython`, and thus Panaroo should continue to run for now after printing this warning.

**Comment by Stellar427** [comment]
Hi,

Thanks for creating panaroo

I installed the tool via mamba .when I try to use panaroo it gives this error:

python3.11/site-packages/Bio/Application/__init__.py:39: BiopythonDeprecationWarning: The Bio.Application modules and modules relying on it have been deprecated.

Due to the on going maintenance burden of keeping command line application
wrappers up to date, we have decided to deprecate and eventually remove these
modules.

We instead now recommend building your command line and invoking it directly
with the subprocess module.
  warnings.warn(
Need specified aligner to be installed

**Comment by ShuyiF** [comment]
Hi @gtonkinhill 

I've met the same issue. I saw you added a commit and see the version 1.5.1. I'm wondering how could I install this updated version?

Looking forward to your reply and thank you in advance!

**Comment by gtonkinhill** [comment]
Hi, sorry for the slow reply. This is now available in the latest release 1.5.1.

**Comment by neranjan007** [comment]
I am using 1.5.1 and it seems i got the same error: 
`/opt/conda/lib/python3.9/site-packages/Bio/Application/__init__.py:40: BiopythonDeprecationWarning: The Bio.Application modules and modules relying on it have been deprecated.

Due to the on going maintenance burden of keeping command line application
wrappers up to date, we have decided to deprecate and eventually remove these
modules.

We instead now recommend building your command line and invoking it directly
with the subprocess module.
  warnings.warn(
Need specified aligner to be installed `
