### ISSUE TITLE
Clustering/Grouping Question

### ISSUE THREAD

**Issue by kneubehl** [gtonkinhill/panaroo#80]
Hello again,

I have encountered a situation where a single copy gene is split into different groups (e.g. group1 for taxa ABD, group2 for taxa CEF, and group3 for taxa G) but the nucleotide identity and the protein identity are both ~80%. The gene is present in all genomes analyzed but would appear to be numerous genes in the analysis instead of the one group it actually is. I tried the --merge_paralogs and even lowering the family ID to 0.5 but they are still different groups. What would cause this?

**Comment by gtonkinhill** [comment]
This would normally be caused by the genes appearing in very different contexts. 

80% identity is below the default threshold for calling genes as paralogs so if each of these groups occurs in a different context the `merge_paralogs` flag would not have an impact.

**Comment by kneubehl** [comment]
That is interesting. The gene is located on the most syntenous plasmid between all the genomes (aside from the chromosome). Looking at an alignment of those plasmids where one plasmid is from each genome being analyzed (see .pdf attached, the gene I keep referring too is marked by an asterisk, you can ignore the blue and red colored arrows) the genes surrounding the gene of interest, at least 2-3 on each side, are conserved across all the genomes. Panaroo splits the gene into 4 groups which is indicated in the .pdf. How much context is panaroo is looking for? 
[plasmid_alignment.pdf](https://github.com/gtonkinhill/panaroo/files/5319318/plasmid_alignment.pdf)

**Comment by gtonkinhill** [comment]
That's interesting, 

I would probably need to take a look at the panaroo input/output to narrow this down further. 

If you are able to send the gffs (or a subset that reproduces the issue) via email I would be happy to take a look.

My email is gqt20@cam.ac.uk

**Comment by alexweisberg** [comment]
I am also having the same issue. I used a single dataset and analyzed it with both panaroo and a method that uses reciprocal best blast + MCL clustering (get_homologues). The results of panaroo split many orthologous genes that were correctly clustered by the more stringent MCL method. 

It would be nice to have an option that allows for these more distantly related genes to group together, which occurs when analyzing a diverse dataset. Perhaps CD-HIT clustering with a stringent threshold to reduce the size of the dataset followed by blast+MCL of representative sequences? Alternatively it would be convenient to be able to provide a pangenome matrix + genomes from another algorithm and apply the pangenome graph cleanup methods to it to further refine the dataset.

Thanks!

**Comment by gtonkinhill** [comment]
I've had a look at some of the example files @kneubehl sent through. 

It turns out this was caused by a number of very diverse plasmids. None of the genes along each plasmid group shared pairwise sequence identity of >95% with any gene in the other plasmids. This can be seen in a snapshot of the Panaroo graph

<img width="744" alt="Screen Shot 2020-10-06 at 12 01 07 AM" src="https://user-images.githubusercontent.com/10625107/95072443-acf9a580-0767-11eb-8f4c-d4556e6693d8.png">

As none of these genes are within 95% pairwise sequence identity there is no context which the algorithm can use to collapse the diverse families. 

The default settings in Panaroo were not chosen for highly diverse datasets and assume that there are at least some genes within the initial 95% identity threshold. This can be adjusted by changing the `--threshold` parameter. 

As an example setting this to 80% pairwise identity (0.8), leads to these plasmids being collapsed as @kneubehl expected, with the 'resT' gene correctly collapsing into one cluster.

<img width="600" alt="Screen Shot 2020-10-06 at 12 02 24 AM" src="https://user-images.githubusercontent.com/10625107/95073002-9ef85480-0768-11eb-83e8-91b70adb93a5.png">

Care should be taken in setting the `--threshold` parameter as setting it too low can lead to over collapsing. For the majority of single species datasets the defaults should be okay as the family collapsing step should handle less common diverse gene families.

In my limited experience in using triangle best-hits algorithms like `get_homologues` they tend to over collapse genes. This can be seen in Figure 4 of the panaroo [paper](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-020-02090-4/figures/4)

**Comment by kneubehl** [comment]
Thanks for the help! I ran the relaxed `--threshold` parameter with` 0.8` and `0.9` and I was able to collapse the resT gene in both instances. I will go with the `0.9` since it will be more stringent. Digging through some of the literature, folks have used 90% as the threshold for CD-HIT clustering with this group of organisms, across the similar species diversity before so that jives. Thanks again!
