### ISSUE TITLE
False Positives

### ISSUE THREAD

**Issue by herber4** [gtonkinhill/panaroo#90]
Hello,

The ultimate goal of my study is to generate a phylogenetic tree based on the core genome with branch values generated from the concatenation of many different gene trees. 

I have ran Panaroo like this: Panaroo -I *.gff -a core --aligner Clustal --clean-mode strict --threshold .98 

Then, to get the single copy genes I opened the final graph, downloaded the node table and sorted the node table based on paralog = 0, and GenomeIDs = all samples. I was thinking that the resulting .aln.fas MSAs would contain 23 sequences, one from each taxa, however, this is not the case. Many of them contain a way more than 23 sequences and look like the attached example, and therefore jam up the IQTREE/RAxML pipeline. 
[group_916.aln.fas.txt](https://github.com/gtonkinhill/panaroo/files/5631136/group_916.aln.fas.txt)

What parameters do I need to change in panaroo so that it the resulting MSAs of the single copy core genes contain only one sequence per taxa? 

Best, 

Austin Herbert

**Comment by gtonkinhill** [comment]
Hi,

This is due to the imperfect way panaroo handles fragmented genes when building alignments. At the moment it will output all fragments into the individual gene files but only takes the longest per sample when generating the concatenated core genome alignment. 

In the alignment you attached you can see that samples 'ICMP661', 'PD8851', 'PD4634' and 'PD885' have a single gene sequence that spans possibly fragmented genes in the other samples. As there are relatively few samples in this dataset panaroo has decided there is not enough evidence to support the fragmented versions and has thus collapsed them into one cluster.
 
![Screen Shot 2020-12-03 at 9 53 14 AM](https://user-images.githubusercontent.com/10625107/100932379-a82b5500-3550-11eb-9456-8f0bc8837c89.png)

Ideally, panaroo would collapse these fragments into a single sequence representation which could be achieved by taking the consensus of the alignment of fragments belonging to the same sample. This is something we are hoping to do in the near future.

In the meantime I would suggest either taking the longest fragment as a representative or if you have the time adjusting your pipeline to take the consensus of fragments from the same sample.

**Comment by herber4** [comment]
Thanks a ton!

**Comment by herber4** [comment]
What is the fastest way to filter out the alignment files that contain more than the taxa sample number?

**Comment by gtonkinhill** [comment]
I like to use [pyfastx](https://pypi.org/project/pyfastx/) for this. If you just want to ignore these alignments entirely you could look at the `gene_presence_absence.csv` file and remove those alignments that include multiple IDs in a single column.
