### ISSUE TITLE
Number of rows in gene_presence_absence.Rtab does not equal number of fasta headers in pan_genome_reference.fa

### ISSUE THREAD

**Issue by sthiede** [gtonkinhill/panaroo#91]
Hi, 

I am using version 1.2.5 of panaroo. 

I noticed that when I run roary, there are N gene sequences in the pan genome fasta and N + 1 lines in the gene_presence_absence.Rtab (+1 for the header). But when I run panaroo, I'm missing 84 genes in the .fa that are in the gene_presence_absence.Rtab (see below). All other gene names match between the rownames in the Rtab and headers in the fasta.

This is happening in strict, moderate, and sensitive modes. And in two different sets of genomes (mine and my labmates). 

```
grep '>' pan_genome_reference.fa | wc -l
4586
wc -l gene_presence_absence.Rtab 
4670 
```

Wondering if this is a bug, or some sort of filtering step I am not understanding? 

Thanks! 
Stephanie

**Comment by gtonkinhill** [comment]
Hi Stephanie,

Apologies for the slow response on this I had to concentrate on getting my PhD submitted. This is expected behaviour in Panaroo. For paralogous gene families we only report one copy of the gene in the pangenome fasta. This helps to avoid alignment issues in downstream analyses.

I hope this helps

**Comment by sthiede** [comment]
Congrats on submitting your PhD! Thank you for the clarification, this helps!
